import test from 'node:test';
import assert from 'node:assert/strict';
import {newDocument,transition,normalizePhone,effectiveStatus,getMetrics} from '../docs/domain.js';
const now=1_800_000_000_000;
function draft(){return {...newDocument({orgId:'auto',title:'Согласование работ',recipient:'Иван Иванов',phone:'+7 (900) 000-00-00'},now),hash:'hash-v1',fileKey:'file-1'};}
function waiting(){return transition(draft(),{type:'send'},{orgId:'auto'},now).doc;}
const context={access:true,viewed:true,version:1,hash:'hash-v1'};
test('Российский номер нормализуется; некорректные данные отклоняются',()=>{assert.equal(normalizePhone('8 (900) 000-00-00'),'79000000000');assert.throws(()=>newDocument({title:'Test',recipient:'Иван',phone:'123'}));});
test('Другая организация не может отправить или отозвать документ',()=>{assert.throws(()=>transition(draft(),{type:'send'},{orgId:'travel'},now));assert.throws(()=>transition(waiting(),{type:'revoke'},{orgId:'travel'},now));});
test('Отправленный документ не редактируется; начальный объект не изменяется',()=>{const d=draft();const w=transition(d,{type:'send'},{orgId:'auto'},now).doc;assert.equal(d.status,'draft');assert.throws(()=>transition(w,{type:'edit',input:{}},{orgId:'auto'},now));});
test('Отозванный документ не подписывается',()=>{const d=transition(waiting(),{type:'revoke'},{orgId:'auto'},now).doc;assert.throws(()=>transition(d,{type:'sign',code:'123456',accepted:true},context,now));});
test('Просроченный документ не допускает новый код',()=>{const d=waiting();assert.equal(effectiveStatus(d,now+73*3600_000),'expired');assert.throws(()=>transition(d,{type:'request_code',purpose:'access'},{},now+73*3600_000));});
test('Пять неверных кодов исчерпывают попытки, даже если затем код правильный',()=>{let d=transition(waiting(),{type:'request_code',purpose:'access'},{},now).doc;const code=d.challenge.code;for(let i=0;i<5;i++){const r=transition(d,{type:'verify_access',code:'000000'},{},now+1000);assert.ok(r.result.error);d=r.doc;}assert.equal(d.challenge.attempts,5);assert.throws(()=>transition(d,{type:'verify_access',code},{},now+2000));});
test('Код нельзя использовать повторно, по истечении срока или вместо другого назначения',()=>{let d=transition(waiting(),{type:'request_code',purpose:'access'},{},now).doc;const code=d.challenge.code;assert.throws(()=>transition(d,{type:'verify_access',code},{},now+301_000));assert.throws(()=>transition(d,{type:'sign',code,accepted:true},context,now));d=transition(d,{type:'verify_access',code},{},now+1000).doc;assert.throws(()=>transition(d,{type:'verify_access',code},{},now+2000));});
test('Подписание привязано к версии, содержимому и условиям',()=>{const d=transition(waiting(),{type:'request_code',purpose:'sign',accepted:true},context,now).doc;const action={type:'sign',code:d.challenge.code,accepted:true};assert.throws(()=>transition(d,action,{...context,version:2},now));assert.throws(()=>transition(d,action,{...context,hash:'other'},now));assert.throws(()=>transition(d,{...action,accepted:false},context,now));const r=transition(d,action,context,now+1000);assert.equal(r.doc.status,'signed');assert.equal(r.doc.proof.hash,'hash-v1');assert.equal(r.doc.proof.demo,true);});
test('Повтор подписания возвращает один результат',()=>{const d=transition(waiting(),{type:'request_code',purpose:'sign',accepted:true},context,now).doc;const a={type:'sign',code:d.challenge.code,accepted:true};const first=transition(d,a,context,now+1000);const second=transition(first.doc,a,context,now+2000);assert.equal(second.doc.proof.id,first.doc.proof.id);assert.equal(second.doc.events.filter(e=>e.type==='signed').length,1);});
test('Показатель исключает примеры, включает отказы до отправки и учитывает помощь',()=>{const d={...waiting(),status:'signed',assisted:false};const assisted={...d,id:'second',assisted:true};const seed={...d,id:'seed',seed:true};const m=getMetrics([d,assisted,seed,draft()],[{id:'refusal'}],now);assert.equal(m.cases,3);assert.equal(m.signed,2);assert.equal(m.independent,1);assert.equal(m.conversion,33);});
